INSERT INTO tb_product (name, description, price) VALUES ('Notebook', 'Melhor notebook para produtividade, jogos e estudo', 2500.0);
INSERT INTO tb_product (name, description, price) VALUES ('PC', 'Melhor gamer com as melhores configurações', 7500.0);
INSERT INTO tb_product (name, description, price) VALUES ('Livro java', 'Aprimore seus conhecimentos para o mercado de desenvolvimento', 120.5);
INSERT INTO tb_product (name, description, price) VALUES ('Livro the lord of the rings', 'Entre nesse mundo de aventura épico', 85.0);
INSERT INTO tb_product (name, description, price) VALUES ('Notebook lenovo', 'Melhor notebook gamer', 2550.0);
INSERT INTO tb_product (name, description, price) VALUES ('Rails for Dummies', 'Expanda seus conhecimento com esse livro excelente', 2500.0);
INSERT INTO tb_product (name, description, price) VALUES ('Smart TV', 'A TV que vai te levar a outro nível de imagem', 6000.0);
INSERT INTO tb_product (name, description, price) VALUES ('smartfone', 'O poder em, suas mão do melhor smartfone do mercado', 3800.0);
INSERT INTO tb_product (name, description, price) VALUES ('tablet', 'Tenha o melhor e todo lugar na palma da sua mão', 4200.0);
INSERT INTO tb_product (name, description, price) VALUES ('Monitor', 'Melhor imagem do mercado com IPS, esse monitor vai te deixar louco', 5000.0);
INSERT INTO tb_product (name, description, price) VALUES ('Mouse', 'Com mais de 1600DPI esse é para aquele gamer pro', 300.55);
INSERT INTO tb_product (name, description, price) VALUES ('Teclado gamer', 'Hora de se destacar naquele FPS, com melhor teclado mecânico', 600.0);
INSERT INTO tb_product (name, description, price) VALUES ('Livro clean code', 'Melhore seu código e se destaque', 100.0);
INSERT INTO tb_product (name, description, price) VALUES ('Livro agile master', 'Torne se um Agile master', 80.2);
INSERT INTO tb_product (name, description, price) VALUES ('Mouse pad', 'Navega com no seu PC com mais conforto', 135.2);
INSERT INTO tb_product (name, description, price) VALUES ('Gabinete', 'Melhor notebook para produtividade, jogos e estudo', 2500.0);
INSERT INTO tb_product (name, description, price) VALUES ('Placa de video', 'A placa de video mais potente do mercado', 6500.0);
INSERT INTO tb_product (name, description, price) VALUES ('Processador', 'Acelere ao máximo seu PC', 400.0);
INSERT INTO tb_product (name, description, price) VALUES ('Memoria', 'Melhore seu desempenho e produtividade', 500.0);
INSERT INTO tb_product (name, description, price) VALUES ('Notebook Vita', 'Melhor notebook para estudo', 3520.0);
